services:
  aruba-tcp:
    image: docker.elastic.co/observability/stream:v0.15.0
    volumes:
      - ./sample_syslog:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: log --start-signal=SIGHUP --delay=5s --addr elastic-agent:9030 -p=tcp /sample_logs/*.log